version: "2"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "netology"
      POSTGRES_USER: "netologyuser"
      POSTGRES_PASSWORD: "netologypass"
    volumes:
      - ./postgres_backup:/usr/local/pgsql/data/
    ports:
      - "5432:5432"
  postgres2:
    image: postgres:12
    environment:
      POSTGRES_DB: "netology"
      POSTGRES_USER: "netologyuser"
      POSTGRES_PASSWORD: "netologypass"
    volumes:
      - ./postgres_backup:/usr/local/pgsql/data/
    ports:
      - "5433:5432"
volumes:
  postgres_data:
  postgres_backup:
