version: "2"
services:
  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: "netology"
      MYSQL_USER: "netologyuser"
      MYSQL_PASSWORD: "netologypass"
      MYSQL_ONETIME_PASSWORD: "netologypass"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
